name: ML
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py39h3811e60_1001
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py39h06a4308_2
  - cffi=1.15.0=py39hd667e15_1
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.0=py39h9ce1e76_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - dnspython=1.16.0=py39h06a4308_0
  - eventlet=0.31.1=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - greenlet=1.1.1=py39h295c915_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9d=h7f8727e_0
  - kiwisolver=1.3.2=py39h295c915_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.5.1=py39h06a4308_0
  - matplotlib-base=3.5.1=py39ha18d171_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h7f8727e_2
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - openssl=1.1.1n=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pillow=9.0.1=py39h22f2fdc_0
  - pip=21.2.4=py39h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - pysocks=1.7.1=py39hf3d152e_4
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - scipy=1.7.3=py39hc147768_0
  - sip=4.19.13=py39h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - tornado=6.1=py39h27cfd23_0
  - tzdata=2021e=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xmltodict=0.12.0=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
      - absl-py==1.0.0
      - aiohttp==3.8.1
      - aiosignal==1.2.0
      - alabaster==0.7.12
      - aniso8601==7.0.0
      - anyio==3.6.1
      - appdirs==1.4.4
      - apsw==3.36.0.post1
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - ase==3.22.1
      - asttokens==2.0.5
      - async-timeout==4.0.2
      - attrs==21.4.0
      - babel==2.10.3
      - backcall==0.2.0
      - band-cal-parallel==0.1.12
      - beautifulsoup4==4.10.0
      - bleach==4.1.0
      - cachetools==4.2.4
      - cftime==1.6.0
      - cif2cell==2.0.0a3
      - click==7.1.2
      - conda-pack==0.6.0
      - cython==0.29.30
      - debugpy==1.5.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - demjson==1.6
      - dill==0.3.5.1
      - distlib==0.3.4
      - docstring-parser==0.12
      - docutils==0.17.1
      - e3nn==0.5.0
      - easydict==1.9
      - ecdsa==0.18.0
      - elasticsearch==7.17.4
      - elasticsearch-dsl==7.4.0
      - entrypoints==0.4
      - executing==0.8.3
      - extxyz==0.1.2
      - fastentrypoints==0.12
      - filelock==3.7.0
      - frozenlist==1.3.0
      - fsspec==2022.2.0
      - future==0.18.2
      - google-auth==2.6.0
      - google-auth-oauthlib==0.4.6
      - gpaw==22.8.1b1
      - grpcio==1.43.0
      - h11==0.12.0
      - h5py==3.6.0
      - httpcore==0.14.7
      - httpx==0.22.0
      - imageio==2.19.3
      - imagesize==1.4.1
      - importlib-metadata==4.11.3
      - ipykernel==6.9.1
      - ipython==8.1.1
      - ipython-genutils==0.2.0
      - ipywidgets==7.6.5
      - jarvis-tools==2022.5.5
      - jedi==0.18.1
      - jinja2==3.0.3
      - jmespath==0.10.0
      - jsonschema==4.4.0
      - jupyter==1.0.0
      - jupyter-client==7.1.2
      - jupyter-console==6.4.3
      - jupyter-core==4.9.2
      - jupyterlab-pygments==0.1.2
      - jupyterlab-widgets==1.0.2
      - latexcodec==2.0.1
      - llvmlite==0.38.0
      - markdown==3.3.6
      - markupsafe==2.1.0
      - matplotlib-inline==0.1.3
      - memoization==0.4.0
      - mistune==0.8.4
      - monty==2022.3.12
      - mpi4py==3.1.3
      - mpitool==0.0.0
      - mpmath==1.2.1
      - msgpack==1.0.3
      - multidict==6.0.2
      - multiprocess==0.70.13
      - natsort==8.1.0
      - nbclient==0.5.13
      - nbconvert==6.4.4
      - nbformat==5.2.0
      - nest-asyncio==1.5.4
      - netcdf4==1.5.8
      - networkx==2.7.1
      - nomad-lab==1.0.8
      - notebook==6.4.8
      - nptyping==1.4.4
      - numba==0.55.1
      - numpy-quaternion==2022.4.1
      - oauthlib==3.2.0
      - opt-einsum==3.3.0
      - opt-einsum-fx==0.1.4
      - orjson==3.6.0
      - palettable==3.3.0
      - pandas==1.4.1
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathos==0.2.9
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pint==0.17
      - platformdirs==2.5.2
      - plotly==5.6.0
      - pox==0.3.1
      - ppft==1.7.6.5
      - prometheus-client==0.13.1
      - prompt-toolkit==3.0.28
      - protobuf==3.19.4
      - psutil==5.9.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-gnuplot==1.1.8
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pybtex==0.24.0
      - pychemia==0.21.9.15
      - pycifrw==4.4
      - pydantic==1.8.2
      - pydeprecate==0.3.1
      - pygments==2.13.0
      - pygnuplot==0.11.16
      - pyleri==1.3.4
      - pymatgen==2022.3.7
      - pymongo==4.1.1
      - pyprocar==5.6.6
      - pyrsistent==0.18.1
      - python-jose==3.3.0
      - python-keycloak==0.26.1
      - pythtb==1.7.2
      - pytorch-lightning==1.5.10
      - pytz==2021.1
      - pyvista==0.35.1
      - pywavelets==1.3.0
      - pyyaml==6.0
      - pyzmq==22.3.0
      - qmpy-rester==0.2.0
      - qtconsole==5.2.2
      - qtpy==2.0.1
      - ray==1.12.0
      - requests==2.26.0
      - requests-oauthlib==1.3.1
      - rfc3986==1.5.0
      - rsa==4.8
      - ruamel-yaml==0.17.21
      - ruamel-yaml-clib==0.2.6
      - schnetpack==1.0.0
      - scikit-image==0.19.3
      - scikit-learn==1.0.2
      - scooby==0.5.12
      - seaborn==0.11.2
      - seekpath==2.0.1
      - send2trash==1.8.0
      - setuptools==59.5.0
      - sisl==0.12.2
      - sniffio==1.2.0
      - snowballstemmer==2.2.0
      - soupsieve==2.3.1
      - spglib==1.16.3
      - spherical-functions==2022.4.1
      - sphinx==5.2.1
      - sphinx-rtd-theme==1.0.0
      - sphinxcontrib-applehelp==1.0.2
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - spinsfast==2022.4.1
      - stack-data==0.2.0
      - style==1.1.0
      - sympy==1.10
      - sympytorch==0.1.1
      - tabulate==0.8.9
      - tb2j==0.7.2.3
      - tenacity==8.0.1
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.5
      - terminado==0.13.3
      - testpath==0.6.0
      - threadpoolctl==3.1.0
      - tifffile==2022.5.4
      - torch==1.11.0+cu113
      - torch-cluster==1.6.0
      - torch-ema==0.3
      - torch-geometric==2.0.4
      - torch-runstats==0.2.0
      - torch-scatter==2.0.9
      - torch-sparse==0.6.13
      - torchaudio==0.11.0+cu113
      - torchmetrics==0.7.2
      - torchvision==0.12.0+cu113
      - tqdm==4.63.0
      - traitlets==5.1.1
      - trimesh==3.12.7
      - typing-extensions==4.1.1
      - typish==1.9.3
      - uncertainties==3.1.6
      - update==0.0.1
      - urllib3==1.26.8
      - virtualenv==20.14.1
      - vtk==9.1.0
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - werkzeug==2.0.3
      - wfn-plot==0.1.2
      - widgetsnbextension==3.5.2
      - wslink==1.6.6
      - yarl==1.7.2
      - zipp==3.7.0
prefix: /data/home/yxma/anaconda3/envs/ML
